### ISSUE TITLE
Add a mobile version to this site

### ISSUE THREAD

**Issue by kaushikom** [OmKaushik71/Landing-page#4]

**Comment by martyn-su** [comment]
<head>
    <meta name="viewpoint" content="width=device-width, initial-scale=1"/>
</head>

**Comment by martyn-su** [comment]
<head>
    <meta name="viewpoint" content="width=device-width, initial-scale=1"/>
</head>

**Comment by almonteluis** [comment]
You want to use a framework or stick with CSS media queries?

**Comment by almonteluis** [comment]
@OmKaushik71

**Comment by kaushikom** [comment]
This issue has been fixed by @nxh01.
